# Generated by Django 4.2.1 on 2023-06-23 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancefpcheck_app', '0002_alter_authentification_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentification',
            name='heure',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 6, 23, 2, 6, 1, 264434), null=True),
        ),
        migrations.AlterField(
            model_name='empreinte',
            name='minutie',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='heure_normale_arrivee',
            field=models.TimeField(default=datetime.datetime(2023, 6, 23, 2, 6, 1, 264434)),
        ),
    ]
