# Generated by Django 4.2.1 on 2023-07-04 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancefpcheck_app', '0004_employee_type_civilite_alter_authentification_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentification',
            name='heure',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 7, 4, 3, 29, 10, 628077), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_civilite',
            field=models.CharField(choices=[('M', 'M'), ('Mme', 'Mme')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='heure_normale_arrivee',
            field=models.TimeField(default=datetime.datetime(2023, 7, 4, 3, 29, 10, 628077)),
        ),
    ]
