# Generated by Django 4.2.1 on 2023-07-04 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancefpcheck_app', '0005_alter_authentification_heure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='prenoms',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='authentification',
            name='heure',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 7, 4, 3, 33, 40, 899929), null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='heure_normale_arrivee',
            field=models.TimeField(default=datetime.datetime(2023, 7, 4, 3, 33, 40, 899929)),
        ),
    ]
