# Generated by Django 4.2.1 on 2023-07-04 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancefpcheck_app', '0006_employee_nom_employee_prenoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentification',
            name='heure',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 7, 4, 3, 36, 20, 399088), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nom',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prenoms',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='heure_normale_arrivee',
            field=models.TimeField(default=datetime.datetime(2023, 7, 4, 3, 36, 20, 399088)),
        ),
    ]
